### ISSUE TITLE
App dies silently when using wrong OpenAI API Key

### ISSUE THREAD

**Issue by nicobrenner** [nicobrenner/commandjobs#45]
If I just copy `src/sample.env` to `.env` and run the app, it will just pass the default text `your_openai_api_key_here` as the key, then fail to get a result, but never display it anywhere visibly - there is no error message

**Comment by aaryamantriescode** [comment]
Hi I would like to look into it.

**Comment by nicobrenner** [comment]
Thank you @aaryamantriescode! Really appreciate it, could you please check if this PR works ok? https://github.com/nicobrenner/commandjobs/pull/46

I just merged it into master

Please let me know if more changes or a better fix is needed
