### ISSUE TITLE
Adding instructions for vim file

### ISSUE THREAD

**Issue by aaryamantriescode** [nicobrenner/commandjobs#58]
Add a section to readme about how to paste your api key some points could be : 
1.to edit the file you need to use delete cause backspace wont work 
2.you need to press insert before editing or else it wont work 
3.to save the file you need to type " :w " plus enter
4.to quit the file you need to type " :q " plus enter

**Comment by nicobrenner** [comment]
This is interesting, and you are right that `vim` is difficult for someone new, there are memes about it and everything

However, `vim` is not a requirement of this project or codebase, you can use any editor to edit the `.env` file

**Comment by aaryamantriescode** [comment]
> This is interesting, and you are right that `vim` is difficult for someone new, there are memes about it and everything
> 
> However, `vim` is not a requirement of this project or codebase, you can use any editor to edit the `.env` file

Ohh makes sense I didn't know that I had to learn how to close/save the file and all😂
