### ISSUE TITLE
wrong table name?

### ISSUE THREAD

**Issue by thepixelmonk** [nicobrenner/commandjobs#7]
`hn_scraping.py` seems to create a table called `new_job_listings` when the rest of the app seems to use `job_listings`.

https://github.com/nicobrenner/commandjobs/blob/9729be6166162e8e27785bebcee8532986125e71/src/hn_scraping.py#L24

**Comment by nicobrenner** [comment]
Hey, thank you so much for checking out the code

There's some cleanup to do there for sure. The code around that was for doing a migration to add a column to a table, getting around some sqlite limitations. The table `new_job_listings` is never used for saving the scraped data

**Comment by nicobrenner** [comment]
It should be fixed with PR #11 

Closing

**Comment by thepixelmonk** [comment]
> Hey, thank you so much for checking out the code
> 
> There's some cleanup to do there for sure. The code around that was for doing a migration to add a column to a table, getting around some sqlite limitations. The table `new_job_listings` is never used for saving the scraped data

How is the `job_listings` table supposed to be initially created? I was just trying to follow the readme but running `python3 menu.py` just errored out due to the table not existing. Also the readme says to run `python3 src/main.py` which doesn't exist so I just assumed I should use `menu.py`.

**Comment by nicobrenner** [comment]
The table `job_listings` should now be created on the first run

Here's the code in `src/database_manager.py`

https://github.com/nicobrenner/commandjobs/pull/11/commits/bbcf0acd40454bd7dded2daef83d04f824eaf449#


```
CREATE TABLE IF NOT EXISTS job_listings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                original_text TEXT,
                original_html TEXT,
                source TEXT,
                external_id TEXT UNIQUE
            )
```

The menu app, in it's init method, creates a new `DatabaseManager` which calls the above in its init method. So when everything is starting up, `DatabaseManager` should be creating the `job_listings` table
