### ISSUE TITLE
Table doesn't exist on first run?

### ISSUE THREAD

**Issue by thepixelmonk** [nicobrenner/commandjobs#8]
This table doesn't seem to exist until you click on the scrape hn button for the first time, but the script just errors out on first run before you can click the button.

https://github.com/nicobrenner/commandjobs/blob/9729be6166162e8e27785bebcee8532986125e71/src/menu.py#L221

**Comment by nicobrenner** [comment]
Thank you. Just checked. You are correct. Currently getting the following error:

```
Traceback (most recent call last):
  File "/repo/src/menu.py", line 354, in <module>
    curses.wrapper(main)
  File "/usr/local/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/repo/src/menu.py", line 350, in main
    app = MenuApp(stdscr, logger)
  File "/repo/src/menu.py", line 31, in __init__
    self.total_listings = self.get_total_listings()
  File "/repo/src/menu.py", line 221, in get_total_listings
    cur.execute("SELECT COUNT(*) FROM job_listings")
sqlite3.OperationalError: no such table: job_listings
```

Looking into it

**Comment by nicobrenner** [comment]
It should be fixed with PR https://github.com/nicobrenner/commandjobs/pull/11

Closing
